---
# Handlers for Postfix notifications.

- name: stop postfix
  service: >
    name={{ postfix_service }}
    state=stopped

- name: start postfix
  service: >
    name={{ postfix_service }}
    state=started
    enabled=yes

- name: restart postfix
  service: >
    name={{ postfix_service }}
    state=restarted
    enabled=yes

- name: refresh virtual map
  command: postmap /etc/postfix/virtual

- name: send test email
  shell: >
    echo "This is a test message from Ansible configuration of {{ ansible_hostname }} at $(date -R)" | sendmail {{ postfix_notify_email }}
  when: postfix_notify_email is defined
