---

- name: Install packages
  apt: name=apache2 state=present
  tags: apache

- name: Copy private key file
  copy:
    src: private.key
    dest: "{{ apache_key_path }}"
    mode: 0600
    owner: root
  tags: apache
  notify: restart apache
- name: Copy certificate file
  copy:
    src: crt.pem
    dest: "{{ apache_certificate_path }}"
    mode: 0644
    owner: root
  tags: apache
  notify: restart apache
- name: Copy chain file
  copy:
    src: ca.pem
    dest: "{{ apache_chain_path }}"
    mode: 0644
    owner: root
  tags: apache
  notify: restart apache

- name: Enable apache mods
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - proxy
    - proxy_http
    - ssl
  tags: apache
  notify: restart apache

- name: Install apache sites
  template:
    src: "{{ item }}.conf.j2"
    dest: /etc/apache2/sites-available/{{ item }}.conf
    mode: 0644
    owner: root
    backup: yes
  with_items:
    - 000-default
    - default-ssl
  tags: apache
  notify:
    - restart apache
- name: Enable apache sites
  command: a2ensite {{ item }}
  args:
    creates: /etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
    - 000-default
    - default-ssl
  tags: apache
  notify:
    - restart apache
