---
- name: Launch a new instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    security_groups:
      - default
      - ssh
  tasks:
    - name: input variables should be defined
      assert:
        that: "hostbasename is defined"
        that: "key_name is defined"
    - name: Launch instance
      ec2:
        key_name: "{{key_name}}"
        group: "{{security_groups}}"
        instance_type: t2.micro
        image: ami-47a23a30
        region: eu-west-1
        vpc_subnet_id: subnet-a21ef4fb
        wait: yes
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{item.public_ip}} groupname=launched
      with_items: ec2.instances
    - name: add new instance to dns
      route53:
        command: create
        zone: mjg78.net
        record: "{{hostbasename}}.mjg78.net"
        type: A
        ttl: 7200
        value: "{{item.public_ip}}"
      with_items: ec2.instances
    - name: wait for ssh
      wait_for: host={{hostbasename}}.mjg78.net port=22 delay=60 timeout=320 state=started

- name: Provision newly created instance
  hosts: launched
  sudo: true
  roles:
    - common
  vars:
    hostname: "{{hostbasename}}.mjg78.net"
