---
# The variables file used for Postfix playbooks.
# If not overriden in inventory or as a parameter, this is the value that will be used

postfix_notify_email: "'mjg'@{{ postfix_domain }}"
postfix_relayhost: ''
postfix_use_smtp: false
postfix_relayhost_user: false
postfix_relayhost_pass: false
